samples: "/data/biol-silvereye/ball6625/dodo/mito-pipeline/config/samples.yaml"
mapdamage_rescale: True
reference_genomes:
  dodo: "Data/ref_genome/dodo/dodo_KX902236.1.fasta"
  solitaire: "Data/ref_genome/solitaire/solitaire_KX902238.1.fasta"
