executor: slurm
jobs: 200
latency-wait: 60
retries: 1

default-resources:
    slurm_partition: "short"
    slurm_account: "biol-silvereye"
    runtime: 15

set-threads:
    bwa_map: 8
    mapdamage2: 8

set-resources:
    bwa_map:
        slurm_partition: "short"
        slurm_account: "biol-silvereye"
        mem_mb: 16000
        runtime: 60
    dedup:
        slurm_account: "biol-silvereye"
        mem_mb: 32000
    mapdamage2:
        slurm_partition: "short"
        slurm_account: "biol-silvereye"
        mem_mb: 8000
        runtime: 60
